# Generated by Django 5.1.4 on 2024-12-24 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_otp_user_otp_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='The phone number should start with 09 and be exactly 11 digits.', regex='09\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='The phone number should start with 09 and be exactly 11 digits.', regex='09\\d{9}$')]),
        ),
    ]
