# Generated by Django 5.1.4 on 2024-12-28 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
